---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list = ls())

library(tidyverse)
library(ggplot2)
library(data.table)
library(lme4)
library(lmerTest)
```

# Distance to man and woman

## Load and clean data

Cosine distances:
```{r}
dat.en = read.csv('../data/matchings/processed/en_data.csv')
dat.es = read.csv('../data/matchings/processed/es_data.csv')
dat.de = read.csv('../data/matchings/processed/de_data.csv')

dat = rbind(dat.en %>% select(-es, -de) %>% mutate(Language='en'), 
            dat.es %>% select(-en, -de) %>% mutate(Language='es'), 
            dat.de %>% select(-en, -es) %>% mutate(Language='de'))

dat = dat %>% rename(NounConcept=translation)
```

# Analyses

## Stats

Contrasts:
```{r}
dat$Rating = factor(dat$Rating)
dat$question = as.numeric(dat$question)
dat$Language = factor(dat$Language, levels=c("en", "es", "de"))   # dummy coding, en is the reference level
dat$NounGroup = as.factor(dat$NounGroup)
contrasts(dat$NounGroup) = contr.sum(2)    # sum coding, mean between man and woman is the reference level
colnames(attr(dat$NounGroup, "contrasts")) = c("groupdiff")
```

Model:
```{r}
m = glmer(Rating ~ Language*NounGroup + scale(question) + (1+Language|NounConcept) + (1+scale(question)|ResponseId), data=dat, family="binomial")
summary(m)
```

## Plot

```{r}
language.labs <- c("English", "Spanish", "German")
names(language.labs) <- c("en", "es", "de")

dat.by_noun = dat %>%
  group_by(NounConcept, Language, NounGroup) %>% summarize(meanRating=mean(as.numeric(Rating)))

p.main = ggplot(data=dat.by_noun, mapping=aes(x=NounGroup, y=meanRating, fill=NounGroup))+
  facet_wrap(~Language, labeller=labeller(Language=language.labs))+
  stat_summary(geom='col', fun='mean',
               width=0.8)+
  stat_summary(geom='errorbar', fun.data='mean_se',
               color = 'black', size = 0.8, width=0)+
  geom_point(position=position_jitter(width=0.2, height=0), 
             size=1, alpha=0.5, shape=21, stroke=1)+
  geom_hline(yintercept=0)+
  coord_cartesian(ylim=c(1,2))+
  scale_fill_manual(values=c("mediumblue", "darkgreen"))+
  scale_y_continuous(breaks = c(1,1.5,2), labels=c("F","","M")) +
  theme_classic()+theme(legend.position="none")
p.main
```

## Compare with embedding distances

```{r}
dat.cosine = read.csv("../data/embeddings/experimental/all_embeddings_experimental_matchings.csv")

dat.cosine.masc = dat.cosine %>% 
  filter(GENDER.ASSOCIATION.OF.ADJECTIVE=='masculine') %>% unique() %>% 
  rename(masculine_adjective=ADJECTIVE, noun=NOUN, Language=LANGUAGE) %>%
  select(-GENDER.ASSOCIATION.OF.ADJECTIVE)
dat.cosine.fem = dat.cosine %>% 
  filter(GENDER.ASSOCIATION.OF.ADJECTIVE=='feminine') %>% unique() %>% 
  rename(feminine_adjective=ADJECTIVE, noun=NOUN, Language=LANGUAGE) %>%
  select(-GENDER.ASSOCIATION.OF.ADJECTIVE)

dat.all = dat %>% select(-RatingType, -version, -NounID) %>%
  merge(dat.cosine.masc) %>% rename(cosine2masc=COSINE.SIMILARITY) %>%
  merge(dat.cosine.fem) %>% rename(cosine2fem=COSINE.SIMILARITY)
```

### Stats

Contrasts:
```{r}
dat.all$Rating = factor(dat.all$Rating)
dat.all$NounConcept = factor(dat.all$NounConcept)
dat.all$ResponseId = factor(dat.all$ResponseId)
dat.all$question = as.numeric(dat.all$question)
dat.all$Language = factor(dat.all$Language, levels=c("en", "es", "de"))   
```

Model:
```{r}
m = glmer(Rating ~ Language + Language:scale(cosine2masc) + Language:scale(cosine2fem) + scale(question) + (1+Language|NounConcept) + (1+scale(question)|ResponseId), data=dat.all, family="binomial")
summary(m)
```

```{r}
m2 = glmer(Rating ~ Language*NounGroup + Language:scale(cosine2masc) + Language:scale(cosine2fem) + scale(question) + (1+Language|NounConcept) + (1+scale(question)|ResponseId), data=dat.all, family="binomial")
summary(m2)
```

```{r}
anova(m2,m)
```

```{r}
dat.all.by_noun = dat.all %>%
  group_by(NounConcept, Language, NounGroup) %>% summarize(cosine2masc=mean(cosine2masc),
                                                           cosine2fem=mean(cosine2fem),
                                                           meanRating=mean(as.numeric(Rating)))

dat.all.mean = dat.all %>%
  group_by(NounConcept, Language, NounGroup, masculine_adjective, feminine_adjective) %>% 
  summarize(cosine2masc=mean(cosine2masc),
            cosine2fem=mean(cosine2fem),
            meanRating=mean(as.numeric(Rating)))

ggplot(data=dat.all.by_noun, mapping=aes(x=cosine2masc, y=meanRating))+
  facet_wrap(~Language)+
  geom_point()+
  theme_classic()
ggplot(data=dat.all.by_noun, mapping=aes(x=cosine2fem, y=meanRating))+
  facet_wrap(~Language)+
  geom_point()+
  theme_classic()
ggplot(data=dat.all.mean, mapping=aes(x=cosine2masc, y=meanRating))+
  facet_wrap(~Language)+
  geom_point()+
  theme_classic()
ggplot(data=dat.all.mean, mapping=aes(x=cosine2fem, y=meanRating))+
  facet_wrap(~Language)+
  geom_point()+
  theme_classic()
```

#COMBINE
```{r}
# actually just have one subplot here
ggsave("plots/Study2.pdf", width=16, height=12, units="cm")

# save table
write.csv(summary(m2)$coefficients, "tables/study2_model_with_cosines.csv")
```